// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUserNameMissing(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NAME_MISSING.String() && e.Code == 400
}

func ErrorUserNameMissing(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_USER_NAME_MISSING.String(), fmt.Sprintf(format, args...))
}

func IsPasswordWrong(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PASSWORD_WRONG.String() && e.Code == 401
}

func ErrorPasswordWrong(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_PASSWORD_WRONG.String(), fmt.Sprintf(format, args...))
}
