// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsStaffnoMissing(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_STAFFNO_MISSING.String() && e.Code == 400
}

func ErrorStaffnoMissing(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_STAFFNO_MISSING.String(), fmt.Sprintf(format, args...))
}

func IsGetstaffFailed(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GETSTAFF_FAILED.String() && e.Code == 500
}

func ErrorGetstaffFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_GETSTAFF_FAILED.String(), fmt.Sprintf(format, args...))
}
