// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/duty/v1/duty.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDutyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDutyRequest) Reset() {
	*x = GetDutyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_duty_v1_duty_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDutyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDutyRequest) ProtoMessage() {}

func (x *GetDutyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_duty_v1_duty_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDutyRequest.ProtoReflect.Descriptor instead.
func (*GetDutyRequest) Descriptor() ([]byte, []int) {
	return file_api_duty_v1_duty_proto_rawDescGZIP(), []int{0}
}

func (x *GetDutyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDutyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	No    string `protobuf:"bytes,2,opt,name=no,proto3" json:"no,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Level int64  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *GetDutyReply) Reset() {
	*x = GetDutyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_duty_v1_duty_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDutyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDutyReply) ProtoMessage() {}

func (x *GetDutyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_duty_v1_duty_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDutyReply.ProtoReflect.Descriptor instead.
func (*GetDutyReply) Descriptor() ([]byte, []int) {
	return file_api_duty_v1_duty_proto_rawDescGZIP(), []int{1}
}

func (x *GetDutyReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDutyReply) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

func (x *GetDutyReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDutyReply) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_api_duty_v1_duty_proto protoreflect.FileDescriptor

var file_api_duty_v1_duty_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x75, 0x74, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x75,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x75,
	0x74, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x75, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x58, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x75,
	0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x32, 0x49, 0x0a, 0x04, 0x44, 0x75, 0x74, 0x79, 0x12, 0x41, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x44, 0x75, 0x74, 0x79, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x75, 0x74, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x75, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x75, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x44, 0x75, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x26, 0x0a, 0x0b,
	0x61, 0x70, 0x69, 0x2e, 0x64, 0x75, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x15, 0x67,
	0x62, 0x6d, 0x65, 0x72, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x75, 0x74, 0x79, 0x2f, 0x76,
	0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_duty_v1_duty_proto_rawDescOnce sync.Once
	file_api_duty_v1_duty_proto_rawDescData = file_api_duty_v1_duty_proto_rawDesc
)

func file_api_duty_v1_duty_proto_rawDescGZIP() []byte {
	file_api_duty_v1_duty_proto_rawDescOnce.Do(func() {
		file_api_duty_v1_duty_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_duty_v1_duty_proto_rawDescData)
	})
	return file_api_duty_v1_duty_proto_rawDescData
}

var file_api_duty_v1_duty_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_duty_v1_duty_proto_goTypes = []interface{}{
	(*GetDutyRequest)(nil), // 0: api.duty.v1.GetDutyRequest
	(*GetDutyReply)(nil),   // 1: api.duty.v1.GetDutyReply
}
var file_api_duty_v1_duty_proto_depIdxs = []int32{
	0, // 0: api.duty.v1.Duty.GetDuty:input_type -> api.duty.v1.GetDutyRequest
	1, // 1: api.duty.v1.Duty.GetDuty:output_type -> api.duty.v1.GetDutyReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_duty_v1_duty_proto_init() }
func file_api_duty_v1_duty_proto_init() {
	if File_api_duty_v1_duty_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_duty_v1_duty_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDutyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_duty_v1_duty_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDutyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_duty_v1_duty_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_duty_v1_duty_proto_goTypes,
		DependencyIndexes: file_api_duty_v1_duty_proto_depIdxs,
		MessageInfos:      file_api_duty_v1_duty_proto_msgTypes,
	}.Build()
	File_api_duty_v1_duty_proto = out.File
	file_api_duty_v1_duty_proto_rawDesc = nil
	file_api_duty_v1_duty_proto_goTypes = nil
	file_api_duty_v1_duty_proto_depIdxs = nil
}
